# === Engine 基础配置 ===
kyuubi.engine.type=SPARK_SQL
kyuubi.engine.spark.master=spark://spark-master:7077
kyuubi.frontend.protocols=THRIFT_BINARY
kyuubi.frontend.thrift.binary.bind.host=0.0.0.0
kyuubi.frontend.thrift.binary.bind.port=10009
kyuubi.authentication=NONE
kyuubi.frontend.rest.bind.port=10099
kyuubi.engine.share.level=USER

# === 关键开关：让 Spark 使用 Hive Metastore ===
spark.sql.catalogImplementation=hive
spark.hadoop.hive.metastore.uris=thrift://172.18.0.1:9083


spark.hadoop.hive.metastore.warehouse.dir=s3a://bronze/warehouse
spark.sql.warehouse.dir=s3a://bronze/warehouse


# 改成本地路径，Metastore 只负责记账，不需要访问 S3
spark.hadoop.hive.metastore.warehouse.dir=/tmp/hive/warehouse
spark.sql.warehouse.dir=/tmp/hive/warehouse

# === Delta Lake 核心配置 ===
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog

# === MinIO / S3 连接配置 ===
spark.hadoop.fs.s3a.access.key=admin
spark.hadoop.fs.s3a.secret.key=admin12345
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem

# === JAR 依赖 ===
spark.jars=/opt/spark/jars/hadoop-aws-3.3.4.jar,/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/spark/jars/delta-core_2.12-2.4.0.jar,/opt/spark/jars/delta-storage-2.4.0.jar
